language: node_js

node_js:
  - '10'

before_script:
  - npm install
  - cd examples && npm install && cd ..

script:
  - npm run lint
  - npm run typecheck
  - npm run test
  - npm run build && npm run bundlesize
  - cd examples && npm run test

notifications:
  email: false
